import NavBar from '@components/NavBar'
import { ReduxProvider } from '@redux/provider'
import '@styles/globals.css'
import { Inter } from 'next/font/google'
// import Notification from '@components/Notification'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Expense Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NavBar />
          {/* <Notification /> */}
          <main>
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  )
}
